### ISSUE TITLE
Behavior for `insert_final_newline = true` is inverted.

### ISSUE THREAD

**Issue by josiahsprague** [schorfES/node-lintspaces#31]
In an `.editorconfig` file when `insert_final_newline = true`, it means that files should end with a blank new line. The lintspaces implementation works in reverse. When I set `insert_final_newline = true` in my `.editorconfig` file, lintspaces complains about all of my files ending with newlines, but that's actually what I want, and I'd like to be able to get an error/warning if a file is *missing* that newline. From the EditorConfig docs;

> `insert_final_newline`: set to `true` ensure file ends with a newline when saving and `false` to ensure it doesn't.

**Comment by schorfES** [comment]
Do you use the lintspaces "core"-api directly or in a grunt or gulp plugin?

Can you checkout the master of node-lintspaces and run the tests using ```grunt test``` because there are [tests for newline feature](https://github.com/schorfES/node-lintspaces/blob/master/tests/newlines/eof.js) and [tests for editorconfig feature](https://github.com/schorfES/node-lintspaces/blob/master/tests/core/editorconfig.js) which currently didn't fail.

**Comment by josiahsprague** [comment]
I'm using gulp-lintspaces, which uses node-lintspaces directly to parse and apply the linting settings. I'll dig into the code and see if I can pinpoint where the problem is originating.

**Comment by schorfES** [comment]
It may belongs to your configuration in the .editorconfig

* have you set ```root = true``` and the file isn't in your root directory / higher than the editorconfig?
* have you set a specific ```[*.ext]``` file extension which doesn't match your linted file?

**Comment by josiahsprague** [comment]
Turns out the issue was that my editor appends an implicit newline to the end of all of my files, so when I was saving them with a manual newline, they ended up having two newlines. `EPEBKAC!`
